### ISSUE TITLE
Consider enabling uploadfile in std/full presets

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4-presets#16]
The plugin itself is very light and as of 4.8.0 we have all other dependencies in the editor: https://github.com/ckeditor/ckeditor-dev/blob/dee99e283ce259f8e16f1092e3d7613a5e45a499/plugins/uploadfile/plugin.js

The benefit of enabling it is that users could drag & drop much more types of files than just images into the editor.

**Comment by f1ames** [comment]
We decided to ditch this idea due to https://github.com/ckeditor/ckeditor4-presets/pull/44#issuecomment-702654228 and https://github.com/ckeditor/ckeditor4-presets/pull/44#issuecomment-702656045.
