### ISSUE TITLE
Include editorplaceholder plugin into preset

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-presets#35]
I suppose it should go into full preset only, but cc @f1ames 

Placeholder text plugin issue: https://github.com/ckeditor/ckeditor4/issues/3793

**Comment by f1ames** [comment]
That's good question, what is the default config for placeholder plugin? I mean what will be the effect or adding it to presets without adjusting any configuration? Will it start to display default placeholder or placeholder text needs to be set explicitly? I wonder how it will affect existing integrations :thinking:

**Comment by jacekbogdanski** [comment]
It won't be visible without explicitly set `placeholdertext` config option.

**Comment by f1ames** [comment]
> It won't be visible without explicitly set `placeholdertext` config option.

So if by default it doesn't change anything we could include it in `full` and `standard` presets. OTOH we have `standard-all` which have this purpose of being `standard` but with all plugins easily available. Let's stick with `full` preset only then, WDYT?

**Comment by jacekbogdanski** [comment]
Sounds good :+1:

**Comment by jacekbogdanski** [comment]
Closed in #38
