### ISSUE TITLE
Copying files on OSX fails

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4-presets#9]
The result of running build.sh on OSX:

```
Copying extra plugins...

usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

64
undefined
```

**Comment by mlewand** [comment]
Note that once this gets checked in, we should check the [duplicated `build.sh` in ckeditor-dev](https://github.com/ckeditor/ckeditor-dev/blob/f3e23c8/dev/builder/build.sh) repo.

**Comment by f1ames** [comment]
I have been using both macOS and Linux for quite a long time with this repo and this issue seems to be non-existent - I assume Darwin behavior got aligned with Linux one. Closing this.
